export default {
  '/welcome':{
    component:require('VIEW/welcome'),
    subRoutes:{
      '/login':{
        name:'login',
        component:require('WELCOME/login')
      },
      '/register':{
        name:'register',
        component:require('WELCOME/register')
      }
    }
  },
  '/log':{
    name:'log',
    needToLogin:true,
    component:require('VIEW/log'),
    subRoutes:{
      '/prjManage':{
        name:'prjManage',
        component:require('CONTENT/prjManage')
      }
    }
  }
}
